# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];


  boot.initrd.luks.devices = {
    crypt0 = {
      device = "/dev/disk/by-partlabel/luks4tb";
      preLVM = true;
    };
    crypt1 = {
      device = "/dev/disk/by-partlabel/luks2tb";
      preLVM = true;
    };
  };


  fileSystems."/" = {
     device = "/dev/nixvg0/root";
     fsType = "ext4";
  };

  fileSystems."/home" = {
     device = "/dev/nixvg0/home";
     fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "dev/disk/by-partlabel/ESP";
    fsType = "vfat";
    options = [ "noatime" "nodiratime" ];
  };

  swapDevices = [
    { device = "/dev/nixvg0/swap";}
  ];
  

#  fileSystems."/" =
#    { device = "/dev/disk/by-uuid/67302cf3-9c1e-4e02-b52f-59767194ce82";
#      fsType = "ext4";
#    };

#  fileSystems."/home" =
#    { device = "/dev/disk/by-uuid/1df8d2f5-f87d-4b4b-b29f-78afd689e5eb";
#      fsType = "ext4";
#    };

#  fileSystems."/boot" =
#    { device = "/dev/disk/by-uuid/CE04-8596";
#      fsType = "vfat";
#      options = [ "fmask=0022" "dmask=0022" ];
#    };

#  swapDevices =
#    [ { device = "/dev/disk/by-uuid/1a7e58c2-17d2-499f-86aa-4041dc839034"; }
#    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp110s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
